Add support for alteeve enterprise repos
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

diff --git a/ci-setup-anvil-bm-vm b/ci-setup-anvil-bm-vm
--- a/ci-setup-anvil-bm-vm
+++ b/ci-setup-anvil-bm-vm
@@ -2,24 +2,58 @@
 
 set -e
 
-VARIANT="$1"
+BUILD="$1"
+REPOSRC="$2"
+ANVILSRC="$3"
 
-case "$VARIANT" in
+case "$BUILD" in
  centos-8-stream)
   SRCURL=https://cloud.centos.org/centos/8-stream/x86_64/images/
   NAME="Centos 8 Stream"
   IMG="GenericCloud"
-  BUILD="centos-8-stream"
   KVMVAR="centos-stream8"
  ;;
  rhel-8)
   NAME="RHEL 8"
-  BUILD="rhel-8"
   KVMVAR="rhel8-unknown"
   CRED="/root/rh-cred"
  ;;
  *)
-  echo "Unknown variant"
+  echo "Unknown build: $BUILD"
+  exit 1
+ ;;
+esac
+
+ANVILDEPS=false
+ALTEEVE=false
+ALTEEVESTAGING=false
+
+case "$REPOSRC" in
+ ci)
+  ANVILDEPS=true
+ ;;
+ enterprise)
+  ALTEEVE=true
+ ;;
+ enterprise-staging)
+  ALTEEVESTAGING=true
+ ;;
+ *)
+  echo "Unknown repo src: $REPOSRC"
+  exit 1
+ ;;
+esac
+
+ANVIL=false
+
+case "$ANVILSRC" in
+ ci)
+  ANVIL=true
+ ;;
+ none)
+ ;;
+ *)
+  echo "Unknown anvil src: $ANVILSRC"
   exit 1
  ;;
 esac
@@ -143,6 +177,13 @@ if [ -n "$CRED" ]; then
  fi
 fi
 
+if [ ! -f "/root/alteeve-key" ]; then
+ echo "Unable to access alteeve-key"
+ exit 1
+fi
+
+AKEY=$(cat /root/alteeve-key)
+
 echo "Generating cloud-init configs"
 SSHKEY="$(cat $DEPLOYDIR/configs/id_rsa.pub)"
 for i in $ALLNODES; do
@@ -164,6 +205,11 @@ for i in $ALLNODES; do
    -e "s#@SSHKEY@#${SSHKEY}#g" \
    -e "s#@KEY@#${KEY}#g" \
    -e "s#@ORG@#${ORG}#g" \
+   -e "s#@AKEY@#${AKEY}#g" \
+   -e "s#@ANVIL@#${ANVIL}#g" \
+   -e "s#@ANVILDEPS@#${ANVILDEPS}#g" \
+   -e "s#@ALTEEVE@#${ALTEEVE}#g" \
+   -e "s#@ALTEEVESTAGING@#${ALTEEVESTAGING}#g" \
    -e "s#@ANVILPKG@# - anvil-${ANVILPKG}#g" \
    > "$DEPLOYDIR/configs/${i}_cloud_init.cfg"
 done
