Add coverity build
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

diff --git a/ci-tests-src b/ci-tests-src
--- a/ci-tests-src
+++ b/ci-tests-src
@@ -6,6 +6,36 @@ case $build in
  rpm)
   exit 0
   ;;
+ coverity)
+  echo "===== CURRENT COVERITY SCAN ERRORS ====="
+  cat cov.txt
+  echo "===== END CURRENT COVERITY SCAN ERRORS ====="
+
+  ret=0
+  # this will trigger only with build-after-merge
+  if [ "${install}" = 1 ]; then
+   mkdir -p /srv/covscan/$DEST/$GIT_BRANCH/
+   mv cov.json cov.txt /srv/covscan/$DEST/$GIT_BRANCH/
+  else
+   csdiff -xc --no-color /srv/covscan/$DEST/$TARGET/cov.json cov.json > cov.diff
+   errors="$(cat cov.diff | grep ^Error: | wc -l)"
+   if [ "$errors" -ne "0" ]; then
+    echo "===== NEW COVERITY SCAN ERRORS FIXED ====="
+    cat cov.diff
+    echo "===== END NEW COVERITY SCAN ERRORS FIXED ====="
+   fi
+   csdiff -c --no-color /srv/covscan/$DEST/$TARGET/cov.json cov.json > cov.diff
+   errors="$(cat cov.diff | grep ^Error: | wc -l)"
+   if [ "$errors" -ne "0" ]; then
+    echo "===== NEW COVERITY SCAN ERRORS DETECTED ====="
+    cat cov.diff
+    echo "===== END NEW COVERITY SCAN ERRORS DETECTED ====="
+    ret=1
+   fi
+  fi
+
+  exit $ret
+  ;;
  *)
   ;;
 esac
